### ISSUE TITLE
Not adding to my daemon

### ISSUE THREAD

**Issue by more-pepsi** [zerowidth/launched#14]
curl -o ~/Library/LaunchAgents/launched.ccenter-torrent.plist 

launchctl load -w ~/Library/LaunchAgents/launched.ccenter-torrent.plist
Load failed: 5: Input/output error
Try running `launchctl bootstrap` as root for richer errors.

**Comment by zerowidth** [comment]
I'd say look at the console app to see if you can find errors, but in the plist you linked (prior to editing the issue), it looks like you misspelled the `--torrent` CLI arg.
