### ISSUE TITLE
Website returns 500

### ISSUE THREAD

**Issue by hons82** [zerowidth/launched#3]
Hey,
I've just tried to generate a plist on your website, but it returns 500
Unfortunately there is not more info on what went wrong.

Best
Hannes

**Comment by zerowidth** [comment]
Sorry about that! Looks like I ran out of allotted number of rows in my free heroku database (thanks spambots) and had my write access revoked. I've cleared up the old data and it should work again.

Potential future improvement: separate "save this plist" from "generate this plist" so it's not as dependent on the database, and adding some rudimentary spam detection... whoo.
