### ISSUE TITLE
Ampersands are escaped in the output plist

### ISSUE THREAD

**Issue by AriYoung00** [zerowidth/launched#4]
For example, say I want the command to be `sh -c brew update && brew upgrade`. The output is `sh -c brew update &amp;&amp; brew upgrade`.

**Comment by zerowidth** [comment]
I've tested this with the newly released log path settings (ref #5), and this is fine -- `&amp;&amp` is valid encoding for `&&` in XML, and it does translate. It's likely that `brew` isn't in the path, i.e. `sh: brew: command not found`.
