### ISSUE TITLE
support logging via StandardOutPath and StandardErrorPath

### ISSUE THREAD

**Issue by felixfischer** [zerowidth/launched#5]
Could support for `StandardOutPath` and `StandardErrorPath` keys be added to launched?

Because that's a nice and simple [way to add logging](http://erikslab.com/2011/02/04/logging-with-launchd/) to your script. Syntax example:

```
<key>StandardOutPath</key>
<string>/var/log/progname.log</string>
```

**Comment by zerowidth** [comment]
This is a great idea, but I don't have time to work on it at the moment.

**Comment by zerowidth** [comment]
At long last, I've added support for this to the new and improved (rails 6 + bootstrap 5) version of this app.
