### ISSUE TITLE
How to start app?

### ISSUE THREAD

**Issue by phathak** [zerowidth/launched#6]
Hey,
I'd like to integrate this great app to my nginx setup but I not familiar with ruby scripts. It is ran on a macOS machine. Can you help me understand how to start your app?

Thank you!

**Comment by zerowidth** [comment]
Unfortunately this is a pretty complicated question. Ruby apps aren't the easiest to get up and running in general, and it's worse on a mac if you want it to run as a daemon.

To just get things running at all, and assuming you have homebrew, here's the commands I ran to get it up and running in development mode (just now, to make sure it all worked):

```
brew install postgres rbenv ruby-build openssl
rbenv install 1.9.3-p551
# cd to the launched directory
gem install bundler
bundle config build.eventmachine --with-cppflags=-I/usr/local/opt/openssl/include
bundle install
createuser -s launched
bundle exec rake db:setup
bundle exec rails server
```

And then load http://localhost:3000.

---

For a more permanent install, you'll have to do some digging through docs and expand on the steps above. In particular, I'd look at the following:

* set up a production database and config (see `config/database.yml`) and use `RAILS_ENV=production` to run things in production mode
* read the rbenv docs to get ahold the paths/commands for the rbenv shims for ruby 1.9.3-p551 plus the bundled gems for this project, so you can invoke the server with the correct entire ruby/gems environment from a fresh session or launchd process
* use this app (ha) to create a plist to start the app on boot or whenever, using the shims from above
* configure nginx to proxy to the rails app

There's a lot of detail I'm glossing over here too, sad to say... 

---

Or, lastly, you could run this on heroku under your account. They'll do most if not all of the hard work for you and you won't have to think about it much.

Good luck!

**Comment by phathak** [comment]
Thank you for the quick and thorough reply! I'll explore those options.
