### ISSUE TITLE
Correct way of unloading a plist

### ISSUE THREAD

**Issue by mjsarfatti** [zerowidth/launched#7]
Hello there,
first of all thanks for the tool, super useful!

One question: shouldn't uninstalling be `launchctl unload -w` (***un***load) as opposed to `launchctl load -w` ?

The /help page might need a correction.

**Comment by arthurhess** [comment]
I came here to ask this. It appears to have been fixed in 2015: https://github.com/zerowidth/launched/pull/2

@zerowidth First, thanks for taking your time developing and publishing this tool. Could you please deploy the latest revision to heroku?

**Comment by zerowidth** [comment]
It was fixed in #2 but deployment has been an issue for awhile; the heroku stack this was on has been fully deprecated since 2019. I've updated the app and released the new version, including the `launchctl unload` changes.
